spring:
  application:
    name: grsu-schedule
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  liquibase:
    change-log: db/liquibase-changelog.xml

grsu:
  api:
    url: http://api.grsu.by/1.x/app2
    langKey: ru_RU
  schedule:
    pullingCron: '0 0 0 * * *'
