spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: grsu-schedule

grsu:
  schedule:
    apiUrl: http://api.grsu.by/1.x/app2
