version: '3'

services:
  postgres:
    container_name: keycloak-postgres
    image: postgres:16.2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass
    networks:
      - keycloak-network
  keycloak:
    image: keycloak/keycloak:24.0
    ports:
      - 8180:8080
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloakdb
      KC_DB_USERNAME: keycloakuser
      KC_DB_PASSWORD: keycloakpass

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: csVdUOTQnSakWVQrXXgzMBAgr

      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm" ]
    networks:
      - keycloak-network
    depends_on:
      - postgres

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local