logging:
  level:
    by.grsu.schedule: debug
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: grsu-schedule

application:
  web:
    cors:
      allowed-headers: '*'
      allowed-methods: '*'
      allowed-origins: 'http://localhost:4200'