logging:
  level:
    by.grsu.schedule: debug
    com.github.benmanes: debug
    org.springframework.cache: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: grsu-schedule
