server:
  error:
    include-stacktrace: never
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: grsu-schedule-client
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/grsu-schedule
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/grsu-schedule
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterAccess=5m
  jackson:
    default-property-inclusion: non_null
  application:
    name: grsu-schedule
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  liquibase:
    change-log: db/liquibase-changelog.xml

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: account

application:
  schedule:
    pulling:
      cron: '0 0 0 * * *'
      startDateOffset: -60
      endDateOffset: 30
      parallelism: 15
  services:
    location-iq:
      enabled: true
      url: https://us1.locationiq.com
      api-key: ${LOCATION_IQ_API_KEY}
      rate-limit: 1.5
      address-format: '%c!,%s!,%h'
    grsu:
      api:
        enabled: true
        url: http://api.grsu.by/1.x/app2
        langKey: ru_RU
  meta:
    display-formats:
      schedule-windows-analytics-module:
        teacher-id: '{surname} {name} {patronym} (ID: {id})'
        group-id: '{title} (ID: {id})'

management:
  endpoints:
    web:
      exposure:
        include: caches,health,info,metrics,prometheus